Add ability to to hide cells and node hashes in `KCFGShow.show()`
runtimeverification/pyk pull request #282
Opened 2023-03-20 21:42 UTC by nwatson22

This PR adds some optional parameters to `KCFGShow.show()` which allow the user to hide the node hashes for the nodes in `nodes`, as well as to hide specified cells, which applies to both the printed nodes, node deltas, and the generated module.

This is intended to be used in K foundry integration to have the option to omit certain information from the `foundry-show` command output that is likely to change for a test case without the behavior of that test case changing. This would be used for certain tests to verify the KCFG of that test does not change modulo node hashes and certain  "volatile" cells.

2023-03-22 08:41 UTC, tothtamas28 requested changes
The diff contains some unrelated changes, please clean up commit history.

2023-03-22 08:41 UTC, tothtamas28 commented on src/pyk/__main__.py
> +    sys.stdout.write('\n')
The diff contains unrelated changes, please clean up commit history.

2023-03-23 02:14 UTC, nwatson22 commented on src/pyk/__main__.py
> +    sys.stdout.write('\n')
I'm not sure how that happened. It should be reverted now.

2023-03-23 08:38 UTC, tothtamas28 approved these changes

2023-03-23 08:39 UTC, tothtamas28 commented
Created an issue related to this part of the code base: https://github.com/runtimeverification/pyk/issues/291

2023-03-23 20:03 UTC, merged