Add `failure_info` method for showing why `APRProof` failed
runtimeverification/pyk pull request #517
Opened 2023-06-28 23:07 UTC by nwatson22

This method was previously in `evm-semantics` and this upstreams it into `pyk`.
Also adds a test which checks the output of this function for `IMP-SIMPLE-SPEC.failing-if`.
The expected output can be updated by running this test while passing the `--update-expected-output` option for `pytest`. This system was also ported from `evm-semantics`.

2023-06-29 07:52 UTC, tothtamas28 requested changes

2023-06-29 07:52 UTC, tothtamas28 commented on src/tests/conftest.py
> +    return request.config.getoption('--update-expected-output')
To be honest, I'm not a big fan of this pattern, as it encourages writing tests that compare string output, which leads to a brittle test suite. This is fine for a few test cases where the string output actually matters (like this current one, though this feature could also be made more testable by introducing an intermediate data structure), but that does not require first-class support from the test harness. Please remove this.

2023-06-29 19:07 UTC, tothtamas28 commented on src/tests/conftest.py
> +    return request.config.getoption('--update-expected-output')
Exactly, looks pretty good.

2023-06-29 19:16 UTC, tothtamas28 approved these changes

2023-06-29 19:16 UTC, tothtamas28 commented on src/pyk/proof/reachability.py
> +class APRFailureInfo:
Consider making this an immutable dataclass:

```python3
@dataclass(frozen=True)
class APRFailureInfo:
    failing: FrozenDict[int, tuple[str, str]]
    pending: frozenset[int]

    def __init__(self, failing: Mapping[int, tuple[str, str]], pending: iterable[int])
         ...

    @staticmethod
    def from_proof(proof: APRProof, explore: KCFGExpore) -> APRFailureInfo:
        ...
```

2023-06-29 19:43 UTC, nwatson22 commented on src/pyk/proof/reachability.py
> +class APRFailureInfo:
Done. Do the changes look ok?

2023-06-30 08:25 UTC, tothtamas28 commented on src/pyk/proof/reachability.py
> +class APRFailureInfo:
Looks good. Consider adding `__init__` with a slightly weaker signarutre:

```python
def __init__(self, failing_nodes: Mapping[int, tuple[str, str]], pending_nodes: iterable[int]):
    object.__setattr__(self, 'failing_nodes', FrozenDict(failing_nodes))
    object.__setattr__(self, 'pending_nodes', frozenset(pending_nodes))
```

2023-06-30 08:25 UTC, tothtamas28 commented on src/pyk/proof/reachability.py
> +    def print(self) -> list[str]:
What's missing is a few simple unit tests for this method.

Once that's done, the original tests will be refactored into:
* A heavier integration test that compares data structures, hence more robust;
* A unit test that does string comparison but runs in an instant, hence easy to iterate on.

Also, this will be the only place where we need to compare these string outputs, so once this PR is merged, the `evm-semantics` test suite can be refactored accordingly.

2023-06-30 17:23 UTC, nwatson22 commented on src/pyk/proof/reachability.py
> +class APRFailureInfo:
Done.

2023-06-30 17:24 UTC, nwatson22 commented on src/pyk/proof/reachability.py
> +    def print(self) -> list[str]:
Added a test for `print()`.

2023-07-03 21:42 UTC, merged