Factor out predicate to Subst logic into `Subst.from_pred` function
runtimeverification/pyk pull request #573
Opened 2023-08-03 00:59 UTC by nwatson22

Closes #525 
Minor refactoring to #519.
@palinatolmach you said there were circular dependency issues. I'm not sure if I caught these.
When I add the necessary imports I do get the error
```
src/pyk/prelude/ml.py:34: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:35: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:48: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:52: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:56: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:60: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:64: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:68: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:72: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:78: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
src/pyk/prelude/ml.py:79: error: Cannot determine type of "GENERATED_TOP_CELL"  [has-type]
```
from the type checker. I don't really know why this happens or if it means there's a deeper problem with the python dependency graph but I was able to make it go away by adding an explicit type annotation to `GENERATED_TOP_CELL`.

2023-08-03 08:16 UTC, tothtamas28 requested changes
Please add unit tests (for both successful cases and exceptions).

2023-08-03 08:16 UTC, tothtamas28 commented on src/pyk/kast/inner.py
> +            m = subst_pattern.match(subst_pred)
Consider using `match-case` instead ([PEP 636](https://peps.python.org/pep-0636/)):

```python3
match subst_pred:
    case KApply(KLabel('#Equals'), KVariable(var), term):
        _subst[var] = term
    case _:
        raise ValueError(...)
```

2023-08-03 08:16 UTC, tothtamas28 commented on src/pyk/kast/inner.py
> +                raise AssertionError(f'Received a non-substitution from get-model endpoint: {subst_pred}')
```suggestion
                raise ValueError(f'Invalid substitution predicate: {subst_pred}')
```

2023-08-03 08:16 UTC, tothtamas28 commented on src/pyk/kast/inner.py
> +    def from_pred(substs_pred: KInner) -> Subst:
```suggestion
    def from_pred(pred: KInner) -> Subst:
```

2023-08-03 08:16 UTC, tothtamas28 commented on src/pyk/kast/inner.py
> +        for subst_pred in _flatten_label('#And', substs_pred):
```suggestion
        for conjunct in _flatten_label('#And', substs_pred):
```

2023-08-03 08:16 UTC, tothtamas28 commented on src/pyk/kast/inner.py
> +        _subst: dict[str, KInner] = {}
```suggestion
        subst: dict[str, KInner] = {}
```

2023-08-03 08:16 UTC, tothtamas28 commented on src/pyk/kcfg/explore.py
> +            return Subst.from_pred(model_subst)
```suggestion
            try:
                return Subst.from_pred(model_subst)
            except ValueError as err:
                raise AssertionError(f'Received a non-substitution from get-model endpoint: {subst_pred}') fro err
```

2023-08-03 08:16 UTC, tothtamas28 commented on src/pyk/prelude/k.py
> +GENERATED_TOP_CELL: Final[KSort] = KSort('GeneratedTopCell')
Type checker should be able to infer that. Are there type errors related to this?

2023-08-03 14:09 UTC, nwatson22 commented on src/pyk/kast/inner.py
> +        def _flatten_label(label: str, kast: KInner) -> list[KInner]:
This is intentionally duplicated because trying to import `flatten_label`  from `kast/manip.py` in `kast/inner.py` results in a circular import error. I was wondering if you had an opinion about the best way to deal with this.

2023-08-03 14:57 UTC, tothtamas28 commented on src/pyk/kast/inner.py
> +        def _flatten_label(label: str, kast: KInner) -> list[KInner]:
What do you think about the two options above?

2023-08-03 23:15 UTC, nwatson22 commented on src/pyk/kast/inner.py
> +            m = subst_pattern.match(subst_pred)
Done.

2023-08-03 23:15 UTC, nwatson22 commented on src/pyk/kast/inner.py
> +                raise AssertionError(f'Received a non-substitution from get-model endpoint: {subst_pred}')
Done.

2023-08-03 23:15 UTC, nwatson22 commented on src/pyk/kast/inner.py
> +        for subst_pred in _flatten_label('#And', substs_pred):
Done.

2023-08-03 23:15 UTC, nwatson22 commented on src/pyk/kast/inner.py
> +        _subst: dict[str, KInner] = {}
Done.

2023-08-03 23:15 UTC, nwatson22 commented on src/pyk/kcfg/explore.py
> +            return Subst.from_pred(model_subst)
Done.

2023-08-03 23:16 UTC, nwatson22 commented on src/pyk/prelude/k.py
> +GENERATED_TOP_CELL: Final[KSort] = KSort('GeneratedTopCell')
I've removed it. It was giving a type error but only when the circular dependency was active.

2023-08-03 23:18 UTC, nwatson22 commented on src/pyk/kast/inner.py
> +        def _flatten_label(label: str, kast: KInner) -> list[KInner]:
The ones I mentioned? I guess I would slightly lean toward keeping the duplicate local function and keep this as a static method of `Subst`.

2023-08-04 07:18 UTC, tothtamas28 commented on src/pyk/kast/inner.py
> +        def _flatten_label(label: str, kast: KInner) -> list[KInner]:
I mean the two options I suggested in this thread. Specifically:

> Okay, now I see this is to avoid introducing circular imports. You can either:
> * Move `flatten_label` to `kast.inner`
> * Import locally

2023-08-04 16:37 UTC, nwatson22 commented on src/pyk/kast/inner.py
> +        def _flatten_label(label: str, kast: KInner) -> list[KInner]:
I changed it to a local import.

2023-08-04 16:37 UTC, nwatson22 commented
Added tests for this function.

2023-08-04 18:29 UTC, tothtamas28 approved these changes

2023-08-04 18:29 UTC, tothtamas28 commented on src/pyk/kast/inner.py
> +            print(conjunct)
```suggestion
```

2023-08-04 18:29 UTC, tothtamas28 commented on src/tests/unit/kast/test_subst.py
> +            _ = Subst.from_pred(pred)
```suggestion
            Subst.from_pred(pred)
```

2023-08-04 19:25 UTC, ehildenb commented on src/pyk/kcfg/explore.py
> +                raise AssertionError(f'Received a non-substitution from get-model endpoint: {model_subst}') from err
Do we need to catch and re-raise this exception?

```suggestion
            return Subst.from_pred(model_subst)
```

The stack trace + original exception should be enough information I guess?

2023-08-04 19:38 UTC, tothtamas28 commented on src/pyk/kcfg/explore.py
> +                raise AssertionError(f'Received a non-substitution from get-model endpoint: {model_subst}') from err
The difference is subtle, but the `AssertionError` suggests that there is a bug in the `get-model` endpoint.

2023-08-04 23:03 UTC, merged