Implement K-REPL server skeleton with Flask
runtimeverification/pyk pull request #58
Opened 2022-10-13 14:46 UTC by tothtamas28

2022-10-13 19:29 UTC, dwightguth commented
Fix the conflicts and I'll review this.

2022-10-14 13:23 UTC, dwightguth requested changes
it doesn't look like this approach has any built in support for the JSON RPC protocol, which means if we're going to use it, we need to explicitly add that layer somewhere. It's not as simple as just receiving json requests and sending a json response; there's a whole protocol with certain structure and certain error reporting that we have to make sure to obey.

2022-10-14 13:23 UTC, dwightguth commented on src/pyk/krepl/client/__init__.py
> +        response = self._request('POST', 'load-raw', json={'term': text})
it seems like we ought to be able to implement these changes in a better way somehow, so that it's more transparent, and we don't have to put a bunch of details about how the requests are sent into the methods here.

2022-10-14 14:10 UTC, tothtamas28 commented on src/pyk/krepl/client/__init__.py
> +        response = self._request('POST', 'load-raw', json={'term': text})
> it doesn't look like this approach has any built in support for the JSON RPC protocol, which means if we're going to use it, we need to explicitly add that layer somewhere

Implementing or pulling in an existing JSON-RPC layer would be relatively straightforward. But I don't think we should use JSON-RPC for the API, as the scope has shifted from RPC towards a web application. In this setting, an [OpenAPI](https://www.openapis.org/) or [GraphQL](https://graphql.org/) interface would make more sense I think.

2022-10-14 14:10 UTC, tothtamas28 commented
> it doesn't look like this approach has any built in support for the JSON RPC protocol, which means if we're going to use it, we need to explicitly add that layer somewhere

Implementing or pulling in an existing JSON-RPC layer would be relatively straightforward. But I don't think we should use JSON-RPC for the API, as the scope has shifted from RPC towards a web application. In this setting, an [OpenAPI](https://www.openapis.org/) or [GraphQL](https://graphql.org/) interface would make more sense I think.

2022-10-14 14:25 UTC, tothtamas28 commented on src/pyk/krepl/client/__init__.py
> +        response = self._request('POST', 'load-raw', json={'term': text})
Here, only method, the path section of the URL and JSON payload is provided. But we can come up with conventions to simplify this further, or use some library to abstract over this layer based on a schema description.

2022-10-20 18:17 UTC, dwightguth commented on src/pyk/krepl/client/__init__.py
> +        response = self._request('POST', 'load-raw', json={'term': text})
I think we ought to be able to make this considerably simpler with a judicious getattr function

2022-10-20 18:51 UTC, tothtamas28 commented on src/pyk/krepl/client/__init__.py
> +        response = self._request('POST', 'load-raw', json={'term': text})
I do not see that solution yet, can you elaborate?

Also, note that this layer will be [replaced](https://github.com/runtimeverification/pyk/blob/930c39d2d669a59e319cf6e341686992853649d8/src/pyk/krepl/client/client.py) by a GraphQL client in the upcoming PR.

2022-10-21 18:36 UTC, dwightguth commented on src/pyk/krepl/client/__init__.py
> +        response = self._request('POST', 'load-raw', json={'term': text})
If this code is getting replaced anyway, it's fine.

2022-10-21 18:36 UTC, dwightguth approved these changes

2022-10-24 12:03 UTC, merged