Refactor _no_cell_rewrite_to_dots
runtimeverification/pyk pull request #703
Opened 2023-10-30 08:49 UTC by anvacaru

Fixes: https://github.com/runtimeverification/kontrol/issues/122

2023-10-30 08:53 UTC, tothtamas28 approved these changes
Can you add a few unit tests that demonstrate the fix?

2023-10-31 14:58 UTC, ehildenb commented
@anvacaru if this code was tested by that change, then the test would be failing now, not passing. A test that isn't catching the bug isn't actually a useful test.

2023-11-01 09:49 UTC, anvacaru commented
I have extracted the `no_cell_rewrite_to_dots` function to create unit tests for it. The test data is extracted from the failing proof in kontrol.

2023-11-01 10:40 UTC, tothtamas28 requested changes

2023-11-01 10:40 UTC, tothtamas28 commented on src/pyk/kcfg/explore.py
> +def no_cell_rewrite_to_dots(term: KInner) -> KInner:
```suggestion
def _no_cell_rewrite_to_dots(term: KInner) -> KInner:
```

2023-11-01 10:40 UTC, tothtamas28 commented on src/tests/unit/test_kcfg.py
> +    term = KApply(
Please minimize this example so that
- it still fails on the original version;
- it still passes on the fixed version.

2023-11-01 16:00 UTC, anvacaru commented on src/pyk/kcfg/explore.py
> +def no_cell_rewrite_to_dots(term: KInner) -> KInner:
Done.

2023-11-01 16:00 UTC, anvacaru commented on src/tests/unit/test_kcfg.py
> +    term = KApply(
Done.

2023-11-03 08:46 UTC, anvacaru commented on src/tests/unit/test_kcfg.py
> +def test__no_cell_rewrite_to_dots() -> None:
I added two new tests :
```python
def test_no_cell_rewrite_to_dots_token() -> None:
    term = KRewrite(
        lhs=KToken(
            token='645326474426547203313410069153905908525362434349',
            sort=KSort(name='Int'),
        ),
        rhs=KVariable(name='ACCOUNTS_FINAL', sort=KSort(name='AccountCellMap')),
    )

    expected = KRewrite(
        lhs=KToken(
            token='645326474426547203313410069153905908525362434349',
            sort=KSort(name='Int'),
        ),
        rhs=KVariable(name='ACCOUNTS_FINAL', sort=KSort(name='AccountCellMap')),
    )
    result = _no_cell_rewrite_to_dots(term)
    assert result == expected
```

and 
```python3
def test_no_cell_rewrite_to_dots_single_account() -> None:
    term = KApply(
        label=KLabel(name='_AccountCellMap_', params=()),
        args=(
            KApply(
                label=KLabel(name='<account>', params=()),
                args=(
                    KApply(
                        label=KLabel(name='<acctID>', params=()),
                        args=(
                            KToken(
                                token='645326474426547203313410069153905908525362434349',
                                sort=KSort(name='Int'),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )

    expected = KApply(
        label=KLabel(name='_AccountCellMap_', params=()),
        args=(
            KApply(
                label=KLabel(name='<account>', params=()),
                args=(
                    KApply(
                        label=KLabel(name='<acctID>', params=()),
                        args=(
                            KToken(token='645326474426547203313410069153905908525362434349', sort=KSort(name='Int')),
                        ),
                    ),
                ),
            ),
        ),
    )
    result = _no_cell_rewrite_to_dots(term)
    assert result == expected
```

Both of them are passing and the `_no_cell_rewrite_to_dots` does not modify the address in the `<acctID>`.

2023-11-03 08:59 UTC, tothtamas28 commented on src/tests/unit/test_kcfg.py
> +def test__no_cell_rewrite_to_dots() -> None:
Then first, let's figure out what the intended behavior of that function is. You can check the `git log` to see who implemented that function, and ask them.

Once it's clear, you can write a few simple tests for that specification. Check with the original author to make sure your tests are correct.

Then with proper test coverage, you can fix / reimplement the function.

2023-11-08 19:24 UTC, ehildenb commented on src/tests/unit/test_kcfg.py
> +def test__no_cell_rewrite_to_dots() -> None:
Are these the examples that were crashing in Kontrol? I guess what we should do is include a est of `implication_failure_reason` that was crashing before, and is not crashing now. So would be good to isolate that example that was crashing, and call `implication_failure_reason` on it in the testing harness, make sure it crashes on master version, and that it doesn't on this version.

2023-11-08 19:26 UTC, ehildenb commented on src/tests/unit/test_kcfg.py
> +def test__no_cell_rewrite_to_dots() -> None:
I don't know if a test of `no_cell_rewrite_to_dots` itself is needed, as much as a test of whether the routine crashes on that input still.

2024-02-27 17:30 UTC, ehildenb commented on src/pyk/kcfg/explore.py
> +    return subst(config)
This should probably be moved to `kast/manip.py`.

2024-03-26 08:36 UTC, anvacaru commented
Closing this one as it got stale.

2024-03-26 08:36 UTC, closed without merging