pretty print kore pattern in `SmtSolverError`
runtimeverification/pyk pull request #972
Opened 2024-03-12 12:38 UTC by ovatman

Closes runtimeverification/kontrol#396
Handels `SmtSolverError`s thrown by the `KoreClient` within `CTermSymbolic`, pretty prints the Kore definition in Kast.

2024-03-13 10:53 UTC, anvacaru commented
Looks good to me! But I would prefer @tothtamas28 to review it as well before merging.

2024-03-13 11:05 UTC, palinatolmach commented on src/pyk/kore/rpc.py
> +            super().__init__(f'Smt solver error: {printer.kore_to_pretty(self.pattern)}')
I'd recommend making "SMT" uppercase since it's an abbreviation, here and below:
```suggestion
            super().__init__(f'SMT solver error: {printer.kore_to_pretty(self.pattern)}')
```

2024-03-13 12:10 UTC, tothtamas28 requested changes

2024-03-13 12:10 UTC, tothtamas28 commented on src/pyk/kore/rpc.py
> +    definition_dir: Path | None
This feature should leave the `KoreClient` and the `kore.prc` module unchanged. Instead, you can implement the error translation in `CTermSymbolic`.

2024-03-14 08:20 UTC, tothtamas28 commented on src/pyk/cterm/symbolic.py
> +            raise RuntimeError(f'\nSMT solver error:\n{pretty_pattern}') from err
You can extract a method:

```python3
def _smt_solver_error(self, err: SmtSolverError) -> RuntimeError:
    kast = self.kore_to_kast(err.pattern)
    pretty_pattern = PrettyPrinter(self._definition).print(kast)
    return RuntimeError(f'\nSMT solver error:\n{pretty_pattern}')
```

Then in all four places:

```suggestion
        except SmtSolverError as err:
            raise self._smt_solver_error(err) from err
```

2024-03-14 08:20 UTC, tothtamas28 commented on src/pyk/cterm/symbolic.py
> +            raise RuntimeError(f'\nSMT solver error:\n{pretty_pattern}') from err
Also, consider removing the leading newline:

```python3
RuntimeError(f'SMT solver error:\n{pretty_pattern}')
```

2024-03-14 10:45 UTC, merged